cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path(r'^$', views.cart_detail, name='cart_detail'),
    path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path(r'^create/$', views.order_create, name='order_create'),
    path("payment/", views.order_payment, name="payment"),
    path("callback/", views.callback, name="callback"),
]

pproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from admin_notification.views import check_notification_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('check/notification', check_notification_view, name="check_notifications"),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from shop.models import products

from django.db.models.fields import CharField
from django.utils.translation import gettext_lazy as _
from .constants import PaymentStatus
from django.contrib.auth.models import User

class Ordernow(models.Model):
    name = CharField(_("Customer Name"), max_length=254, blank=False, null=False)
    amount = models.FloatField(_("Amount"), null=False, blank=False)
    status = CharField(
        _("Payment Status"),
        default=PaymentStatus.PENDING,
        max_length=254,
        blank=False,
        null=False,
    )
    provider_order_id = models.CharField(
        _("Order ID"), max_length=40, null=False, blank=False
    )
    payment_id = models.CharField(
        _("Payment ID"), max_length=36, null=False, blank=False
    )
    signature_id = models.CharField(
        _("Signature ID"), max_length=128, null=False, blank=False
    )

    def __str__(self):
        return f"{self.id}-{self.name}-{self.status}"

MYCITY=(
    ('Amritsar','Amritsar'),
    ('Bathinda','Bathinda'),
    ('Barnala','Barnala'),
    ('Bajakhana','Bajakhana'),
    ('Bhucho Mandi','Bhucho Mandi'),
    ('Dabawali','Dabawali'),
    ('Faridkot','Faridkot'),
    ('Goniana','Goniana'),
    ('Jaito','Jaito'),
    ('Jalandhar','Jalandhar'),
    ('Khanna','Khanna'),
    ('Kaliawali','Kaliawali'),
    ('Kotakpura','Kotakpura'),
    ('Ludhiana','Ludhiana'),
    ('Malout','Malout'),
    ('Maur Mandi','Maur Mandi'),
    ('Malerkotla','Malerkotla'),
    ('Moga','Moga'),
    ('Muktsar','Muktsar'),
    ('Patiala','Patiala'),
    ('Rajpura','Rajpura'),
    ('Rampura','Rampura'),
    ('Sunam','Sunam'),
    ('Sangrur','Sangrur'),
    ('Talwandi Sabo','Talwandi Sabo'),
)
class Order(models.Model):
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    email = models.EmailField()
    phone_number=models.CharField(max_length=10,default="")
    address = models.CharField(max_length=150)
    
    city = models.CharField(max_length=100,choices=MYCITY)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    delivery_date=models.CharField(max_length=10,default="")
    userid=models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())



class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(products, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order
from django.contrib.auth.models import User

class OrderCreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user=kwargs.pop('user')
        super(OrderCreateForm, self).__init__(*args, **kwargs)
        self.fields['userid']=forms.ModelChoiceField(label="user",widget=forms.HiddenInput(attrs={'value':user}),queryset=User.objects.all())
        self.fields['delivery_date'].widget = forms.TextInput(attrs={
            'id': 'date',
            })
        
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email','phone_number', 'address',  'city','delivery_date','userid']
    
        

orders/views.py
from django.shortcuts import render
from .models import *
from .forms import OrderCreateForm
from cart.cart import Cart
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
import json
import razorpay
import random
from django.http import HttpResponse
from django.http import JsonResponse


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST,initial={'userid':request.user.id},user=request.user)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item['product'],
                    price=item['price'],
                    quantity=item['quantity']
                )
            #cart.clear()
        return render(request, 'orders/order/created.html', {'order': order})
    else:
        form = OrderCreateForm(initial={'userid':request.user.id},user=request.user)
    return render(request, 'orders/order/create.html', {'form': form})


def order_payment(request):
    if request.method == "POST":
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        orderid=request.POST.get("provider_order_id")
        client = razorpay.Client(auth=(settings.RAZORPAY_KEY_ID, settings.RAZORPAY_KEY_SECRET))
        razorpay_order = client.order.create(
            {"amount": float(amount) * 100, "currency": "INR", "payment_capture": "1"}
        )
        order = Ordernow.objects.create(
            name=name, amount=amount, provider_order_id=razorpay_order['id']
        )
        order.save()
        o1=Order.objects.get(id=orderid)
        o1.paid=True
        o1.save()
        return render(
            request,
            "orders/order/payment.html",
            {
                "callback_url": "http://127.0.0.1:8000/orders/callback/",
                "razorpay_key": settings.RAZORPAY_KEY_ID,
                "order": order,
            },
        )
    return render(request, "orders/order/payment.html")


@csrf_exempt
def callback(request):
    cart = Cart(request)
    razorpay_client = razorpay.Client(auth=(settings.RAZORPAY_KEY_ID,settings.RAZORPAY_KEY_SECRET))
    #    return client.utility.verify_payment_signature(response_data)

    if request.method == "POST":
        try:
            payment_id = request.POST.get("razorpay_payment_id", "")
            provider_order_id = request.POST.get("razorpay_order_id", "")
            signature_id = request.POST.get("razorpay_signature", "")
            params_dict={
                'razorpay_order_id':provider_order_id,
                'razorpay_payment_id':payment_id,
                'razorpay_signature':signature_id

            }
            print(params_dict)
            try:
                order = Ordernow.objects.get(provider_order_id=provider_order_id)
            except:
                return HttpResponse("505 not found inner")
            order.payment_id = payment_id
            order.signature_id = signature_id
            order.save()
            cart.clear()
            result=razorpay_client.utility.verify_payment_signature(params_dict)
            
            if result==True:
                amount=int(order.amount)
                
                try:
                   
                    '''res=razorpay_client.payment.capture(payment_id,{
                        "amount" : amount,
                        "currency" : "INR"
                        })
                    print(res)'''
                    order.status=PaymentStatus.SUCCESS
                    order.save()
                    return render(request, "orders/order/sucess.html")
                except:
                   
                    order.status=PaymentStatus.FAILURE
                    order.save()
                    return render(request, "orders/order/failure.html")
            else:
                
                order.status=PaymentStatus.FAILURE
                order.save()
                return render(request, "orders/order/failure.html")
        except:
            return HttpResponse("505 not found here")

orders/templates/orders/order/create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Checkout
{% endblock %}

{% block content %}

<script>
    $(document).ready(function(){
        $("#ordercreate input").addClass("form-control");
    });
  </script>

        <div class="row bg-light p-5">
            <div class="col-md-12">
                <h4 class="page-header" style="text-align:center; font-size:39px; color:black;">Fill Your Details</h4>
            </div>
        </div>
        <div class="row bg-light" id="ordercreate">
            <div class="col-md-10 ">
                <form action="" method="post" class="forms text-center offset-2">
                    {% csrf_token %}
                    {{ form.as_p }}<br>
                    
                    <center><input type="submit" id="submitbtn"  class="btn btn-dark" value="Submit order"></center>
                </form>
            </div>
        </div>
        
        <script>
            $(document).ready( function() {
                $(function() {
                  $("#date").datepicker( { 
                    minDate: +10, 
                    maxDate: '+1M',
                  beforeShowDay: jQuery.datepicker.noWeekends
                  } );
                });
              });
              </script>
{% endblock %}

orders/templates/orders/order/created.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Thank you
{% endblock %}

{% block content %}
	
        <div class="row bg-light p-5">
          <div class="col-md-12 text-center">
            <h1>Order Placed</h1>
          </div>
        </div>
      
    <div class="container">
        <div class="row" style="margin-top: 6%">
            <div class="col-md-12 text-center">
                <h3 class="page-header">Please click the button to proceed and do not refresh the page.
                </h3>
                <form action="{% url 'orders:payment' %}" method='POST'>
                  {% csrf_token %}
                  <input type="hidden" name="name" value="{{ order.email }}">
        <input type="hidden" name="provider_order_id" value="{{ order.id }}">
        <input type="hidden" name="amount" value="{{ cart.get_total_price }}">
                  
                  <div>
                  <button type="submit" id="btnpay" class="btn btn-dark">Redirect to Payment</button>
                  </div>
                </form>
                
            </div>
        </div>
    </div>
   
{% endblock %}

orders/templates/orders/order/failure.html
{% extends 'base.html' %}
{% block title %}
    Payment Failure
{% endblock %}
{% block content %}

<div class="row bg-light ps-5">
    <div class="col-md-12 ps-5 p-5" id="paysuccess">
        failure!payment has not recieved yet.
    </div>
</div>

{% endblock %}

orders/templates/orders/order/payment.html
{% extends 'base.html' %}
{% block title %}
    Payment
{% endblock %}
{% block content %}
<div class="col-md-12 text-center p-5" >
    <!--<form action="{% url 'orders:payment' %}" method='POST'>
        {% csrf_token %}-->
        
        <div>
        <button type="submit" id="btnpay" class="btn btn-dark ">Pay Now</button>
        </div>
     <!-- </form>-->
</div>

<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
    
var options = {
    key: "{{razorpay_key}}",
    amount: "{{order.amount}}", 
    currency: "INR",
    name: "{{order.name}}",
    description: "Test Transaction",
    image: "https://www.pngfind.com/pngs/m/303-3031049_blello-mattress-mattress-hd-png-download.png",
    order_id: "{{order.provider_order_id}}",
    callback_url: "{{callback_url}}",
    redirect: true,
    prefill: {
        "name": "{{ order.name }}",
        "email": "{{ user.email }}",
        "contact": "9999999999"
    },
    notes: {
        "address": "Mattress"
    },
    theme: {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);
document.getElementById("btnpay").onclick=function(e)
{
rzp1.open();
e.preventDefault();
}
</script>



{% endblock %}

orders/templates/orders/order/sucess.html
{% extends 'base.html' %}
{% block title %}
    Payment Success
{% endblock %}
{% block content %}

<div class="row ps-5 bg-light">
    <div class="col-md-12 p-5 ps-5" id="paysuccess">
        Congratulations!You have successfully done the payment.
    </div>
    <div class="row">
        <div class="col-md-12 text-center p-5">
            <h1>Thanks For Shopping</h1>
            <h2>You will get a confirmation mail from us within 2 hours</h2>
        </div>
    </div>
</div>


{% endblock %}