cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path(r'^$', views.cart_detail, name='cart_detail'),
    path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

pproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from admin_notification.views import check_notification_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('check/notification', check_notification_view, name="check_notifications"),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, include
from shop import views
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView,PasswordResetDoneView, PasswordResetConfirmView,PasswordResetCompleteView
urlpatterns = [
    
    path('furniture/',views.furnitureview.as_view()),
    path('extra/',views.extraview.as_view()),
    path('contact/',views.contactview.as_view()),
    path('aboutus/',views.aboutusview.as_view()),
    path('faq/',views.faqview),
    path('reviews/',views.reviewsview.as_view()),
    path('insertcontact/',views.insertcontact),
    path('blogs/',views.blogview),
    path('blogdetail/<int:id>',views.blogdetailview),
    path('signup/',views.signup),
    path('login/',LoginView.as_view(),name="login"),
    path('logout/',LogoutView.as_view(),name="logout"),
    path('category/',views.categoryview),
    path('product/<int:id>',views.productview),
    path('productdetail/<int:id>',views.productdetailview),
    path('search_res/',views.searchview),
    path('gallery/',views.galleryview),
    path('myorder/',views.myorderview),
    path('insertreview/',views.insertreview),
    path('password-reset/', PasswordResetView.as_view(template_name='registration/password_reset.html'),name='password-reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),name='password_reset_complete'),
]

shop/models.py
from django.db import models
from tinymce.models import HTMLField
from django.contrib.auth.models import User

class contact(models.Model):
    fname=models.CharField(max_length=100)
    lname=models.CharField(max_length=100)
    email=models.CharField(max_length=50)
    message=models.TextField()
    class Meta:
        db_table="contact"

class blog(models.Model):
    title=models.CharField(max_length=100)
    description=HTMLField()
    photo=models.ImageField(upload_to='blog/')
    postby=models.CharField(max_length=50)
    poston=models.DateField()
    class Meta:
        db_table="blog"
    def __str__(self):
        return self.title
    

class faq(models.Model):
    question=models.TextField()
    answer=models.TextField()
    class Meta:
        db_table="faq"
    def __str__(self):
        return self.question
    

class category(models.Model):
    title=models.CharField(max_length=200)
    photo=models.ImageField(upload_to='category/')
    class Meta:
        db_table="category"
    def __str__(self):
        return self.title

MYTAG=(
    ('bestselling','bestselling'),
    ('latest','latest'),
    ('new','new'),
)
class products(models.Model):
    title=models.CharField(max_length=200)
    rating=models.FloatField(default="1.1",blank="true",null="true")
    sellingprice=models.FloatField()
    material=models.CharField(max_length=200)
    description=HTMLField()
    photo=models.ImageField(upload_to='product/',default="")
    photo1=models.ImageField(upload_to='product/',default="")
    photo2=models.ImageField(upload_to='product/',default="")
    size=models.CharField(max_length=100)
    color=models.CharField(max_length=100)
    style=models.CharField(max_length=100)
    categoryid=models.ForeignKey(category,on_delete=models.CASCADE)
    tag=models.CharField(max_length=50,choices=MYTAG)
    class Meta:
        db_table="product"
    def __str__(self):
        return self.title


class gallery(models.Model):
    photo=models.ImageField(upload_to='gallery/')
    class Meta:
        db_table="gallery"




   

class review(models.Model):
    name=models.CharField(max_length=200)
    email=models.CharField(max_length=100)
    
    message=models.CharField(max_length=1000)
    userid=models.ForeignKey(User,on_delete=models.CASCADE)
    proid=models.ForeignKey(products,on_delete=models.CASCADE)    
    class Meta:
        db_table="review"

shop/forms.py
from django import forms
from shop.models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
class contactform(forms.ModelForm):
    class Meta:
        fields='__all__'
        model=contact

class signupform(UserCreationForm):
    class Meta:
        fields=('first_name','last_name','email','username','password1','password2')
        model=User

class reviewform(forms.ModelForm):
    class Meta:
        fields='__all__'
        model=review

shop/views.py
from django.shortcuts import render , redirect
from django.views.generic import TemplateView
from shop.forms import *
from django.contrib.auth import login
from orders.models import *
from cart.forms import CartAddProductForm
# Create your views here.
class aboutview(TemplateView):
    template_name="about.html"
class bootview(TemplateView):
    template_name="boot1.html"
class startbootview(TemplateView):
    template_name="bootstrap.html"
class forestview(TemplateView):
    template_name="forest.html"
class formview(TemplateView):
    template_name="forms.html"
class furnitureview(TemplateView):
    template_name="furniture.html"
class extraview(TemplateView):
    template_name="extra.html"
class contactview(TemplateView):
    template_name="contact.html"
class aboutusview(TemplateView):
    template_name="aboutus.html"
class reviewsview(TemplateView):
    template_name="reviews.html"

def insertcontact(request):
    if request.method=='POST':
        form=contactform(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/furniture/')  
    else:
        form=contactform()
    return render(request,"contact.html",{'form':form})


def blogview(request):
    blg=blog.objects.all().order_by('-poston')
    return render(request,"blogs.html",{'blg':blg})

def blogdetailview(request,id):
    b=blog.objects.get(id=id)
    return render(request,"blogdetail.html",{'b':b})

def faqview(request):
    fraq=faq.objects.all()
    return render(request,"faq.html",{'fraq':fraq})

def signup(request):
    if request.method=="POST":
        form=signupform(request.POST)
        if form.is_valid():
            user=form.save()
            login(request,user)
            return redirect("/furniture/")
    else:
        form=signupform()
    return render(request,"registration/signup.html",{'form':form})

def categoryview(request):
    catg=category.objects.all()
    return render(request,"category.html",{'catg':catg})


def productview(request,id):
    p=products.objects.filter(categoryid_id=id).order_by('-id')
    return render(request,"product.html",{'p':p})

def productdetailview(request,id):
    p=products.objects.get(id=id)
    cart_add_product_form=CartAddProductForm()
    return render(request,"productdetail.html",{'p':p,'cart_add_product_form':cart_add_product_form})

def searchview(request):
    srh=request.GET['searchbox']
    p=products.objects.filter(title__icontains=srh)
    context={'p':p}
    return render(request, 'search-result.html', context)


    
def galleryview(request):
    gall=gallery.objects.all()
    return render(request,"gallery.html",{'gall':gall})

def myorderview(request):
    o=OrderItem.objects.select_related('order').filter(order__userid=request.user.id)
    return render(request,"myorder.html",{'o':o})

def insertreview(request):
    if request.method=='POST':
        form=reviewform(request.POST)
        next=request.POST.get('next')
        if form.is_valid():
            form.save()
            return redirect(next)  
    else:
        form=reviewform()
    return render(request,"productdetail.html",{'form':form})



    

shop/templates/aboutus.html
{% extends 'base.html'%}
{%load static%}
{% block title %}About Us{% endblock %}
{%block content%}

<div class="row p-5 bg-light">
    <div class="col-md-6 ps-5 p-5" data-aos="zoom-in-right" id="aboutid">
        <img src="{% static 'images/shopimage.jpg' %}" height="550px"  width="100%" />
    </div>
    <div class="col-md-6 ps-5 p-5">
        <h1>A Quality in League of Its Own</h1>
        <h4 class="natural">Natural Materials</h4>
        <p class="real">With a real variety of miscellaneous types of furniture offered, we're always making sure to choose only the best of organic and natural materials for it.</p>
        <h4 class="natural">Premium-grade Quality</h4>
        <p class="real">Crafting furniture for different kinds of customers means preserving the same kind of a quality of all pieces. We do that by making sure that the quality is more prioritized than the pace of work, so that every single furniture piece we make is made to last!</p>
        <h4 class="natural">Affordable Pricing</h4>
        <p class="real">As the furniture is one of the most basic needs of an household might have, we never capitalize on the premium quality of our pieces. We always ensure that our pricing policy is fair enough as to allow middle-class to purchase it without a second thought!</p>
        <a href="/gallery/">
            <button class="btn btn-light border-dark" id="gallery">Furniture Gallery</button>
        </a>
    </div>
</div>
<!--row end-->
<div class="row bg-light p-5">
    <div class="col-md-12 ps-5">
        <h1 class="ps-5">We Deliver To</h1>
    </div>
    <div class="row">
        <div class="col-md-3 ps-5" id="deliver1">
            <p class="ps-5">Amritsar</p>
            <p class="ps-5 moga">Bathinda</p>
            <p class="ps-5">Bhucho Mandi</p>
            <p class="ps-5 moga">Talwandi Sabo</p>
            <p class="ps-5">Rampura</p>
            <p class="ps-5 moga">Maur Mandi</p>
        </div>
        <div class="col-md-3 ps-5" id="deliver1">
            <p class="ps-5 moga">Faridkot</p>
            <p class="ps-5">Moga</p>
            <p class="ps-5 moga">Dabawali</p>
            <p class="ps-5">Jaito</p>
            <p class="ps-5 moga">Sunam</p>
            <p class="ps-5">Sangrur</p>
        </div>
        <div class="col-md-3 ps-5" id="deliver1">
            <p class="ps-5">Patiala</p>
            <p class="ps-5 moga">Kotkapura</p>
            <p class="ps-5">Malout</p>
            <p class="ps-5 moga">Ludhiana</p>
            <p class="ps-5">Jalandhar</p>
            <p class="ps-5 moga">Barnala</p>
        </div>
        <div class="col-md-3 ps-5" id="deliver1">
            <p class="ps-5 moga">Bajakhana</p>
            <p class="ps-5">Kaliawali</p>
            <p class="ps-5 moga">Malerkotla</p>
            <p class="ps-5">Khanna</p>
            <p class="ps-5 moga">Muktsar</p>
            <p class="ps-5">Rajpura</p>
        </div>
    </div>
</div>
<!--row end-->
{% endblock %}

shop/templates/base.html
{% load static%}

<!--  header content  -->
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'furniture.css' %}" type="text/css" rel="stylesheet" />
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
        <link href="{% static 'css/bootstrap-grid.min.css' %}" rel="stylesheet" />
        <link href="{% static 'aos-master/dist/aos.css' %}" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Sassy+Frass&display=swap" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css" rel="stylesheet" />
        <!-- Bootstrap CSS -->
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css'>
<!-- Font Awesome CSS -->
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>
<link href="//code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" rel="stylesheet" />
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" type="text/javascript" defer="defer"></script>
        <script src="{% static 'jquery.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'aos-master/dist/aos.js' %}"></script>
        <script>
            AOS.init();
        </script>
        <script>
        $(document).ready(function(){
            AOS.init();
        });
        </script>
    </head>
    <body>
      <div class="container-fluid">
        <div class="row p-4 bg-dark text-light">
             
                      <div class="col-md-4">
                        <nav>
                          <ul class="nav" id="showroom11">
                        <li><a href="/furniture/" class="nav-link text-light">Furniture shop</a></li>
                      </ul> 
                      </nav>
                      </div>
                      <div class="col-md-6">
                          <nav>
                              <ul class=" nav">
                                  
                               
                              
                                  
                                  <li><a href="/contact/" class="nav-link text-light">Contact Us</a></li>
                                  
                                  
                                  <li><a href="/faq/" class="nav-link text-light">FAQs</a></li>
                                  
                                  <li><a href="/category/" class="nav-link text-light">Shop</a></li>
                                  <li><a href="/blogs/" class="nav-link text-light">Blog</a></li>
                                 {% if user.is_authenticated %}
                                 <li><a href="/myorder/" class="nav-link text-light">My order</a></li>
                                  <li><a class="nav-link text-light">Hi,{{user.first_name}}</a></li>
                                  <li><a href="/logout/" class="nav-link text-light">Logout</a></li>

                                  {% else %}
                                  {% endif%}   


                              </ul>
                          </nav>
                      </div>
                      <div class="col-md-2">
                        <nav>
                          <ul class="nav">
                            <li><a href="{%url 'cart:cart_detail' %}" class="nav-link text-light"> <i class='bx bx-cart-alt bx-md'></i>
                            </a></li>
                            {% if user.is_authenticated %}
                            {% else %}
                       
                        
                       <li><a href="/login/" class="nav-link text-light"> <i class='bx bx-user bx-md'></i></a></li>
                       {% endif %}
                        </ul>  
                        </nav>
                    </div>
                  </div>
              

{% block content%}
{% endblock%}
<div class="row bg-dark p-5">
  <div class="col-md-4 p-5">
    <h3  class="text-light ps-3">Our Store Location</h3>
     <p class="text-secondary outlet p-3">Ganga Furniture Showroom,Near Factory Outlet Bhucho Mandi</p>
  </div>
  <div class="col-md-4 p-5 ps-5">
    <h3 class="text-light">FAQ</h3>
    <ul class="nav">
        <li><a href="/faq/" class="nav-link text-secondary ps-0">What methods of payment are accepted?</a></li>
        <li><a href="/faq/" class="nav-link text-secondary ps-0">What is your return policy?</a></li>
        <li><a href="/faq/" class="nav-link text-secondary ps-0">How long is your warranty?</a></li>
        <li><a href="/faq/" class="nav-link text-secondary ps-0">How long does shipping take?</a></li>
    </ul>
  </div>
  <div class="col-md-4 p-5 ps-5">
    <h3 class="text-light">Get to Know Us</h3>
    <nav>
      <p><a href="/aboutus/" class="nav-link text-secondary ps-0 fonthome">About Us</a></p>
        <p><a href="/contact/" class="nav-link text-secondary ps-0 fonthome p-0">Contact Us</a></p>
    </nav>
  </div>
  <div class="col-md-12">
      <br>
      <hr class="style1 text-light">
      <br>
      <p class="text-center text-light">© 2023 Ganga Showroom, All Rights Reserved</p>
  </div>
</div>
</div>
</body>
</html>

<!--  footer content  -->

shop/templates/blogdetail.html
{% extends 'base.html'%}
{%load static%}
{% block title %}Blogs{% endblock %}
{%block content%}

<div class="row">

 
    <div class="col-md-12 p-5">
        
            <h2 data-aos="zoom-in-right">{{ b.title }}</h2>
            <img src="/media/{{ b.photo }}" width="100%" height="500" data-aos="flip-left" />
            <p class="safe11">{{ b.description|safe }}</p>
            <p class="post fw-bold">{{ b.postby }} ({{ b.poston }})</p>
    

    </div>

</div>
{% endblock %}

shop/templates/blogs.html
{% extends 'base.html'%}
{%load static%}
{% block title %}Blogs{% endblock %}
{%block content%}

<div class="row">
    <div class="col-md-12 text-center fw-bold bg-light  p-5 blog1"  data-aos="fade-up-right">
        INSPIRATION AND IDEAS FOR YOUR HOME
    </div>
    {% for b in blg %}
    <div class="col-md-4 p-5 ps-5" id="blogpic"  data-aos="flip-left"
    data-aos-easing="ease-out-cubic"
    data-aos-duration="2000">
        <a href="/blogdetail/{{ b.id }}" class="text-decoration-none text-dark">
            <h2>{{ b.title }}</h2>
            <div class="overflow-hidden">
            <img src="/media/{{ b.photo }}" class="roundedcorners" width="100%" height="250" />
            </div>
            <p class="fw-bold">{{ b.postby }} ({{ b.poston }})</p>
        </a>

    </div>
{% endfor %}
</div>
{% endblock %}

shop/templates/category.html
{% extends 'base.html'%}
{%load static%}
{% block title %}Category{% endblock %}
{%block content%}

<div class="row">
    <div class="col-md-12 text-center fw-bold bg-light  p-5 blog1" >
        OUR FURNITURE COLLECTION
    </div>
    {% for c in catg %}
    <div class="col-md-4 p-5 ps-5"   data-aos="flip-left"
    data-aos-easing="ease-out-cubic"
    data-aos-duration="2000">   
            <a href="/product/{{ c.id }}" class="text-decoration-none">
            <h2 class="text-center text-dark">{{ c.title }}</h2>
            <div class="overflow-hidden">
            <img src="/media/{{ c.photo }}" class="roundedcorners" width="100%" height="250" />
            </div>
           </a>
       

    </div>
{% endfor %}
</div>


{% endblock %}

shop/templates/contact.html
{% extends 'base.html'%}
{%load static%}
{% block title %}Contact Us{% endblock %}
{%block content%}


                <div class="row ps-5 p-5" data-aos="fade-down">
                  <div class="col-md-4 ps-5 p-5 spacing">
                    <div class="bg-light p-5 text-center">
                    <i class="fa-solid fa-location-dot icon2"></i>
                    <h4>Location</h4>
                    <p>Ganga Furniture Gallery,Bhucho Mandi</p>
                    </div>
                  </div>

                  <div class="col-md-4 ps-5 p-5 spacing">
                    <div class="bg-light p-5 text-center">
                    <i class="fa-solid fa-envelope icon2"></i>
                    <h4>Email Address</h4>
                      <a href="mailto:gangasgallery@gmail.com"><p class="text-dark emailsize">Gangasgallery@gmail.com</p></a>
                    </div>
                  </div>

                  <div class="col-md-4 ps-5 p-5 spacing">
                    <div class="bg-light p-5 text-center">
                    <i class="fa-solid fa-phone icon2"></i>
                    <h4>Contact Number</h4>
                    <a href="tel:9465918902"><p class="text-dark">9417138901</p></a>
                    </div>
                  </div>
                </div>

                <!--row  end-->
                <div class="row ps-0 margin p-5">
                  <div class="col-md-6 ps-0">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d27581.69827297104!2d75.07593136991208!3d30.216758209357195!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3910ce215f320f9f%3A0x4cf632610e4c3ef5!2sGANGA%20FURNITURE%20GALLERY!5e0!3m2!1sen!2sin!4v1676616989438!5m2!1sen!2sin" width="100%" height="550px" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                  </div>

                  <div class="col-md-6 border">
                    <form action="/insertcontact/" method="post">
                      {% csrf_token %}
                      <input type="text"  name="fname" class="form-control p-4 form" placeholder="First Name" pattern="[A-Za-z ]*" required/>
                      <input type="text" name="lname" class="form-control p-4 form" placeholder="Last Name" pattern="[A-Za-z ]*" required/>
                      
                      <input type="email" name="email" class="form-control p-4 form" placeholder="E-Mail"/>
                      <textarea name="message" class="form-control p-4 form" placeholder="Message"></textarea>
                      <button type="submit" class="btn btn-success form">Send Message</button>
                    </form>
                  </div>
                </div>
                <!--row end-->
{% endblock%}       

shop/templates/faq.html
{% extends 'base.html'%}
{%load static%}
{% block title %}FAQ{% endblock %}
{%block content%}
<div class="row">
  <div class="col-md-12 text-center p-5 bg-light faq1" >
    <h1  data-aos="fade-up-left">FAQ</h1>
    <p  data-aos="fade-up-left">Find the answers for the most frequently asked questions below</p>
  </div>
  {% for f in fraq %}
  <div class="col-md-4 p-5 bg-light" data-aos="zoom-in-up">
    <div class="bg-white p-5 height1">
   <h4>{{ f.question }}</h4>
   <p class="answer">{{ f.answer }}</p>
   </div>
  </div>
  {% endfor %}
  </div>
  <div class="row">
    <div class="col-md-12 bg-light p-5">
  <p class=" fw-bold text-center message1">For any further query, Kindly <span><a href="/contact/" class="messageus">Message us</a></span></p>
</div>
</div>

{% endblock %}

shop/templates/gallery.html
{% extends 'base.html'%}
{%load static%}
{% block title %}Gallery{% endblock %}
{%block content%}


<div class="row">
    <div class="col-md-12 text-center p-5 bg-light" >
      <h1  data-aos="fade-up-left">Gallery</h1>
    </div>
    {% for g in gall %}
    <div class="col-md-4 p-5" data-aos="zoom-in-up">
      <div class="bg-white p-5">
     <img src="/media/{{ g.photo }}" class="roundedcorners" width="100%" height="250" />
     </div>
    </div>
    {% endfor %}
    </div>



{% endblock %}

shop/templates/java3.html
<html>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <body>
        <input type="password" placeholder="Password" id="pass" />
        <button onclick="showhide()"><i id="icon" class="fa fa-eye"></i></button>
        <input type="password" placeholder="Confirm Password" onkeyup="f(this.value)" />
        <p id="p1"></p>
    </body>
    <script>
        function showhide()
        {
            let p=document.getElementById("pass");
            let icon=document.getElementById("icon");
            if(p.type=="password")
            {
                p.type="text";
                icon.classList.add("fa-eye-slash");
                icon.classList.remove("fa-eye");
            }
            else{
                p.type="password";
                icon.classList.add("fa-eye");
                icon.classList.remove("fa-eye-slash");

            }
        }
        function f(cp)
        {
            let p=document.getElementById("pass").value;
            let para=document.getElementById("p1");
            if(p==cp)
            {
                para.innerHTML="Password match";
                para.style.color="green";
            }
            else{
                para.innerHTML="Password do not match";
                para.style.color="red";
            }
        }
    </script>
</html>

shop/templates/productdetail.html
{% extends 'base.html'%}
{% load static %}
{% block title %}Product Detail{% endblock %}
{%block content%}

<div class="row">
  <div class="col-md-6 p-5 ps-5">
        <img src="/media/{{ p.photo }}" width="100%" height="500" data-aos="flip-left" />
        <div class="row">
            <div class="col-md-6" id="blogpic">
                <img src="/media/{{ p.photo1 }}" width="100%" height="200" data-aos="flip-left" />
            </div>
            <div class="col-md-6" id="blogpic">
                <img src="/media/{{ p.photo2 }}" width="100%" height="200" data-aos="flip-left" />
            </div>
        </div>
    </div>
    <div class="col-md-6 p-5">
        <h2 data-aos="zoom-in-right">{{ p.title }}</h2>
        
            
            <h3>Rs.{{p.sellingprice}}</h3>
            
                <hr class="style1 text-dark">
           
            <p class="text-secondary material11"><span class=" text-dark material11 fw-bold">Material: </span>{{p.material}}</p>
            <p class="text-secondary material11"><span class="text-dark material11 fw-bold">Size: </span> {{p.size}}</p>
            <p class="text-secondary material11"><span class="text-dark material11 fw-bold">Color: </span>{{p.color}}</p>
            <p class="text-secondary material11"><span class="text-dark materail11 fw-bold">Style: </span>{{p.style}}</p>
            <p class="text-secondary material11"><span class="text-dark materail11 fw-bold">Tag: </span>{{p.tag}}</p>
            
            <hr class="style1 text-dark">
            <h4>About This Item</h4>
            <p class="safe15 text-secondary">{{ p.description|safe}}</p>
    </div>
    <form action="{% url 'cart:cart_add' p.id %}" method="post">
        {% csrf_token %}
        {{ cart_add_product_form }}
        <div class="p-5">
        <input type="submit" value="Add to Cart" class="btn btn-dark">
        </div>
    </form>
</div>



<div  class="row bg-light ps-5">
    <div class="col-md-6">
        {% if user.is_authenticated %}
        <form action="/insertreview/" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label><h3 class="p-3">Post a Review</h3></label>
            <input type="hidden" value="{{ request.path }}" name="next" />
            <input class="form-control" type="hidden" value="{{ user.first_name }}" name="name" placeholder="Enter Your Name" /><br>
            <input class="form-control" type="hidden" name="email" value="{{ user.email }}" placeholder="Enter Your Email" /><br>

            <textarea class="form-control" name="message" placeholder="Post your review"></textarea><br>
            <input type="hidden" name="userid" value="{{ user.id }}" />
            <input type="hidden" name="proid" value="{{ p.id }}" />
            <button class="btn btn-info" type="submit">Submit Now</button>
        </form>
        {% else %}
        <a href="/login/?next={{ request.path }}" class="btn btn-dark">Login if you want to give review</a>
        {% endif %}
    </div>
    
</div>


{% endblock %}